version: "3"
services:
  db-local:
    build: ./docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "membership-console-iam"
      MYSQL_USER: "membership-console-iam"
      MYSQL_PASSWORD: "membership-console-iam"
      MYSQL_ROOT_PASSWORD: "membership-console-iam"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/log/local:/var/log/mysql
      - ./docker/mysql/db:/var/lib/mysql
  db-test:
    build: ./docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "membership-console-iam"
      MYSQL_USER: "membership-console-iam"
      MYSQL_PASSWORD: "membership-console-iam"
      MYSQL_ROOT_PASSWORD: "membership-console-iam"
      TZ: "Asia/Tokyo"
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/log/test:/var/log/mysql