spring:
  datasource:
    url: jdbc:mysql://localhost:3306/membership-console-iam?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: membership-console-iam
    password: membership-console-iam
    driver-class-name: com.mysql.cj.jdbc.Driver