spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/iam?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2}
    username: ${MYSQL_USERNAME:iam}
    password: ${MYSQL_PASSWORD:iam}
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    outOfOrder: false
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    connect-retries: 5
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jws-algorithms: RS512

springdoc:
  swagger-ui:
    doc-expansion: none

server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      cookie:
        same-site: strict
        path: /
  forward-headers-strategy: framework
  reactive:
    session:
      timeout: 3h

project:
  name: iam
  version: 1.0.0-SNAPSHOT
  package: cc.rits.membership.console.iam
  url: ${APPLICATION_URL:http://localhost:4200}
  password-reset-url: ${project.url}/password_reset
  mybatis:
    config:
      file: generatorConfig.xml
    model:
      package: infrastructure.db.entity
    client:
      package: infrastructure.db.mapper.base
      type: XMLMAPPER
    map:
      package: db.mapper.base

sendgrid:
  enabled: ${SENDGRID_ENABLED:false}
  api-key: ${SENDGRID_API_KEY}
  from:
    name: Membership Console事務局
    email: ${SENDGRID_EMAIL}

auth:
  session-timeout: 86400 # 24h

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapperLocations:
    - classpath:/db/mapper/base/*Mapper.xml
    - classpath:/db/mapper/*Mapper.xml

logging:
  level:
    root: INFO