spring:
  datasource:
    url: jdbc:mysql://localhost:3307/iam?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: iam
    password: iam
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1

project:
  password-reset-url: http://localhost:4200/password_reset

sendgrid:
  enabled: false
  api-key: SENDGRID_API_KEY
  from:
    name: Membership Console事務局
    email: SENDGRID_EMAIL